version: '3.9'

services:

  nginx:
    #image: nginx_kev
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www:/var/www:rw
    networks:
      - mynet
    depends_on:
      - wordpress
    env_file:
      - .env

  wordpress:
    #image: wordpress_kev
    build: ./wordpress
    volumes:
      - www:/var/www:rw
    networks:
      - mynet
    depends_on:
      - mariadb
    env_file:
      - .env

  mariadb:
    build: ./mariadb
    networks:
      - mynet
    env_file:
      - .env


networks:
  mynet:
    driver: bridge

volumes:
  www:
