version: '3.9'

services:

  nginx:
    #image: nginx_kev
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - www:/var/www:rw
    networks:
      - mynet
    depends_on:
      - wordpress

  wordpress:
    #image: wordpress_kev
    build: ./wordpress
    volumes:
      - www:/var/www:rw
      - shared:/shared:rw
    networks:
      - mynet
    depends_on:
      - mariadb
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}

  mariadb:
    build: ./mariadb
    networks:
      - mynet
    volumes:
      - shared:/shared:rw
    environment:
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} 
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

networks:
  mynet:
    driver: bridge

volumes:
  www:
  shared:
